# Generated by Django 5.0.4 on 2024-04-15 16:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('menu', '0004_product_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='images/'),
        ),
    ]
